apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-all-in-one
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/TykTechnologies/demo-argo-selfmanaged.git'
    path: production/jaeger-configuration
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
