apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 18.12.1
    helm:
      parameters:
        - name: image.tag
          value: 6.2.13
        - name: auth.existingSecret
          value: tyk-redispgsql-secrets
        - name: auth.password
          value: redis-password
    chart: redis
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tyk
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
