apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin-go
spec:
  name: httpbin-go
  protocol: http
  active: true
  use_keyless: true
  detailed_tracing: true
  proxy:
    target_url: http://go-httpbin-service.services.svc.cluster.local
    listen_path: /httpbin-go
    strip_listen_path: true