apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-config-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/TykTechnologies/demo-argo-selfmanaged'
    path: production/tyk-config-secrets
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tyk
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

