apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 12.12.10
    helm:
      parameters:
        - name: auth.database
          value: tyk_analytics
        - name: image.tag
          value: 15.5.0-debian-11-r18
        - name: global.postgresql.auth.existingSecret
          value: tyk-redispgsql-secrets
    chart: postgresql
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tyk
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
