apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-httpbin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-httpbin
  template:
    metadata:
      labels:
        app: go-httpbin
    spec:
      containers:
      - name: go-httpbin
        image: mccutchen/go-httpbin:v2.13.4
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-httpbin-service
spec:
  selector:
    app: go-httpbin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
