apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oas-services
  namespace: argocd
spec:
  destination:
    namespace: services
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/caroltyk/tyk-apiops-demo'
    path: oas-httpbin
    targetRevision: staging
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
